apiVersion: v1
kind: Service
metadata:
  name: tours-service
spec:
  type: NodePort   # Use NodePort for Minikube
  selector:
    app: tours
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
